apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.storeId }}-mysql
  labels:
    app.kubernetes.io/name: woocommerce
    app.kubernetes.io/instance: {{ .Values.storeId }}
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: mysql
    protocol: TCP
    name: mysql
  selector:
    app.kubernetes.io/name: woocommerce
    app.kubernetes.io/instance: {{ .Values.storeId }}
    app.kubernetes.io/component: database
