apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.storeId }}-mysql-secret
  labels:
    app.kubernetes.io/name: woocommerce
    app.kubernetes.io/instance: {{ .Values.storeId }}
    app.kubernetes.io/component: database
type: Opaque
stringData:
  mysql-root-password: {{ .Values.mysql.rootPassword | quote }}
  mysql-password: {{ .Values.mysql.password | quote }}
  mysql-database: {{ .Values.mysql.database | quote }}
  mysql-user: {{ .Values.mysql.user | quote }}
