apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.storeId }}-wordpress
  labels:
    app.kubernetes.io/name: woocommerce
    app.kubernetes.io/instance: {{ .Values.storeId }}
    app.kubernetes.io/component: application
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: woocommerce
    app.kubernetes.io/instance: {{ .Values.storeId }}
    app.kubernetes.io/component: application
