{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  postgres-password: {{ .Values.postgresql.password | quote }}
  postgres-user: {{ .Values.postgresql.user | quote }}
  postgres-db: {{ .Values.postgresql.database | quote }}
{{- end }}
