{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.storeName }}-postgres
  labels:
    app: {{ .Values.storeName }}-postgres
spec:
  serviceName: {{ .Values.storeName }}-postgres
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.storeName }}-postgres
  template:
    metadata:
      labels:
        app: {{ .Values.storeName }}-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_DB
          value: {{ .Values.postgres.auth.database }}
        - name: POSTGRES_USER
          value: {{ .Values.postgres.auth.username }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgres.auth.password }}
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.postgres.primary.persistence.size }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.storeName }}-postgres
spec:
  clusterIP: None
  selector:
    app: {{ .Values.storeName }}-postgres
  ports:
  - port: 5432
    name: postgres
{{- end }}
