{{- if .Values.mysql.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.storeName }}-mysql
  labels:
    app: {{ .Values.storeName }}-mysql
spec:
  serviceName: {{ .Values.storeName }}-mysql
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.storeName }}-mysql
  template:
    metadata:
      labels:
        app: {{ .Values.storeName }}-mysql
    spec:
      {{- if .Values.securityContext.enabled }}
      securityContext:
        runAsNonRoot: false
        runAsUser: 999
        fsGroup: 999
      {{- end }}
      containers:
      - name: mysql
        image: mysql:8.0
        {{- if .Values.securityContext.enabled }}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
              - ALL
            add:
              - NET_BIND_SERVICE
              - CHOWN
              - SETUID
              - SETGID
        {{- end }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mysql.auth.existingSecret | default (printf "%s-mysql-secret" .Values.storeName) }}
              key: mysql-root-password
        - name: MYSQL_DATABASE
          value: {{ .Values.mysql.auth.database }}
        - name: MYSQL_USER
          value: {{ .Values.mysql.auth.username }}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mysql.auth.existingSecret | default (printf "%s-mysql-secret" .Values.storeName) }}
              key: mysql-password
        ports:
        - containerPort: 3306
          name: mysql
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - mysqladmin ping -h localhost -p$MYSQL_ROOT_PASSWORD
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - mysql -h localhost -u root -p$MYSQL_ROOT_PASSWORD -e "SELECT 1"
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        {{- if .Values.mysql.primary.resources }}
        resources:
          {{- toYaml .Values.mysql.primary.resources | nindent 10 }}
        {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.mysql.primary.persistence.size }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.storeName }}-mysql
spec:
  clusterIP: None
  selector:
    app: {{ .Values.storeName }}-mysql
  ports:
  - port: 3306
    name: mysql
{{- end }}
